#!/usr/bin/env node
/**
 * Full Phase 3 pipeline: message -> parse -> validate -> merge -> branch ->
 * commit -> push -> (PR via gh, or a compare link if gh isn't available).
 *
 * Unlike cli/chat.ts (Phase 2, read-only preview), this DOES write files
 * and DOES push a branch to origin. It never touches main directly and
 * never merges/applies anything — that's still entirely up to a human via
 * the GitHub PR UI, same as if they'd done every step by hand.
 *
 * Environment allowlist: only environments in ALLOWED_ENVIRONMENTS (default
 * "dev") are proposable, per the phased rollout plan. Set
 * ALLOWED_ENVIRONMENTS=dev,qa to widen it.
 *
 * Usage:
 *   npm run propose -- "<your request>"
 *   npm run propose -- --file request.txt
 *
 * Prefer --file on Windows: some shell/npm.cmd/cmd.exe combinations have
 * been observed corrupting multi-word quoted arguments (literal "^"
 * characters inserted before spaces) before they ever reach this process.
 * Reading from a file sidesteps shell argument quoting entirely.
 */
import { parseIntent } from "../intent/client.js";
import { mergeEntry } from "../modelwriter/index.js";
import {
  createChangeBranch,
  writeAndCommit,
  pushBranch,
  openPullRequest,
  returnToMain,
} from "../gitprovider/index.js";
import { readMessage } from "./readMessage.js";

async function main() {
  const { message } = readMessage(process.argv.slice(2));
  if (!message) {
    console.error(
      'Usage: npm run propose -- "<your request>"  (or: npm run propose -- --file request.txt)'
    );
    process.exit(1);
  }

  const allowedEnvironments = (process.env.ALLOWED_ENVIRONMENTS ?? "dev")
    .split(",")
    .map((e) => e.trim());

  console.log(`[1/5] Parsing intent...`);
  const result = await parseIntent([{ role: "user", content: message }]);

  if (result.kind === "clarification") {
    console.log(`[clarification needed] ${result.question}`);
    return;
  }
  if (result.kind === "no_action") {
    console.log(`[no action] ${result.message}`);
    return;
  }

  console.log(
    `[2/5] Proposal: ${result.resourceType} / ${result.environment} / ${result.key}`
  );
  if (!result.validation.valid) {
    console.error(`[validation FAILED]`);
    result.validation.errors.forEach((e) => console.error(`  - ${e}`));
    process.exitCode = 1;
    return;
  }
  console.log(`[validation OK]`);

  if (!allowedEnvironments.includes(result.environment)) {
    console.error(
      `[blocked] Environment "${result.environment}" is not in ALLOWED_ENVIRONMENTS=${allowedEnvironments.join(",")}. ` +
        `This is a deliberate safety gate, not a bug — widen ALLOWED_ENVIRONMENTS only when you're ready to let the chatbot propose changes to that environment.`
    );
    process.exitCode = 1;
    return;
  }

  const merge = mergeEntry(
    result.resourceType,
    result.environment,
    result.key,
    result.fields
  );
  if (!merge.validation.valid) {
    console.error(`[merged file validation FAILED]`);
    merge.validation.errors.forEach((e) => console.error(`  - ${e}`));
    process.exitCode = 1;
    return;
  }

  console.log(`[3/5] Creating branch and committing...`);
  const branchPrefix = `chatbot/${result.environment}-${result.key}`;
  const branch = createChangeBranch(branchPrefix);
  const commitMessage =
    `Add ${result.key} ${result.resourceType} (${result.environment})\n\n` +
    `Proposed via chatbot from: "${message}"\n\n` +
    `Schema-validated before commit; not yet reviewed by a human.`;
  writeAndCommit(merge.filePath, merge.after, commitMessage);

  console.log(`[4/5] Pushing branch ${branch}...`);
  pushBranch(branch);

  console.log(`[5/5] Opening pull request...`);
  const prTitle = `Add ${result.key} ${result.resourceType} (${result.environment})`;
  const prBody =
    `**Generated by chatbot — human review required.**\n\n` +
    `Original request: "${message}"\n\n` +
    `Resource type: \`${result.resourceType}\`\n` +
    `Environment: \`${result.environment}\`\n` +
    `Key: \`${result.key}\`\n\n` +
    "```json\n" +
    JSON.stringify(result.fields, null, 2) +
    "\n```";
  const pr = openPullRequest(branch, prTitle, prBody);

  returnToMain();

  if (pr.prUrl) {
    console.log(`\nPR opened: ${pr.prUrl}`);
  } else {
    console.log(
      `\nBranch pushed, but "gh" isn't installed/authenticated so the PR wasn't opened automatically.`
    );
    console.log(`Open it here (one click, pre-filled): ${pr.compareUrl}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
