import { validateEntry } from "../validators/index.js";
import { mergeEntry } from "../modelwriter/index.js";
import {
  createChangeBranch,
  writeAndCommit,
  pushBranch,
  openPullRequest,
  returnToMain,
} from "../gitprovider/index.js";
import type { ProposeOutcome } from "./proposeInfrastructureChange.js";

/**
 * Same end state as proposeInfrastructureChange.ts (branch -> commit -> push
 * -> PR), but skips the Claude intent parser entirely. The frontend chat
 * widget collects resourceType/environment/key/fields directly from a form
 * built off models/schema/*.schema.json (see GET /schema-info), so there is
 * no free-text natural language to interpret here — just validate and go.
 *
 * Kept as a separate function (not a mode flag on proposeInfrastructureChange)
 * because it has no "message" to record and no clarification/no_action path
 * — the shape of what can go wrong is different from the LLM path.
 */
export async function proposeStructuredChange(
  resourceType: string,
  environment: string,
  key: string,
  fields: Record<string, unknown>,
  requesterId?: string
): Promise<ProposeOutcome> {
  const allowedEnvironments = (process.env.ALLOWED_ENVIRONMENTS ?? "dev")
    .split(",")
    .map((e) => e.trim());

  const validation = validateEntry(resourceType, fields);
  if (!validation.valid) {
    return { status: "validation_failed", errors: validation.errors };
  }

  if (!allowedEnvironments.includes(environment)) {
    return { status: "environment_blocked", environment, allowed: allowedEnvironments };
  }

  const merge = mergeEntry(resourceType, environment, key, fields);
  if (!merge.validation.valid) {
    return { status: "merged_file_invalid", errors: merge.validation.errors };
  }

  const branchPrefix = `chatbot/${environment}-${key}`;
  const branch = createChangeBranch(branchPrefix);

  const requestedBy = requesterId ? `\nRequested by: ${requesterId}` : "";
  const commitMessage =
    `Add ${key} ${resourceType} (${environment})\n\n` +
    `Proposed via chatbot form (structured input, no LLM parsing).${requestedBy}\n\n` +
    `Schema-validated before commit; not yet reviewed by a human.`;
  writeAndCommit(merge.filePath, merge.after, commitMessage);

  pushBranch(branch);

  const prTitle = `Add ${key} ${resourceType} (${environment})`;
  const prBody =
    `**Generated by chatbot — human review required.**\n\n` +
    `Submitted via the fixed-schema chat form (no free-text LLM parsing involved).${requestedBy}\n\n` +
    `Resource type: \`${resourceType}\`\n` +
    `Environment: \`${environment}\`\n` +
    `Key: \`${key}\`\n\n` +
    "```json\n" +
    JSON.stringify(fields, null, 2) +
    "\n```";
  const pr = openPullRequest(branch, prTitle, prBody);

  returnToMain();

  if (pr.prUrl) {
    return {
      status: "pr_opened",
      resourceType,
      environment,
      key,
      fields,
      branch,
      prUrl: pr.prUrl,
    };
  }
  return {
    status: "pushed_no_pr",
    resourceType,
    environment,
    key,
    fields,
    branch,
    compareUrl: pr.compareUrl,
  };
}
