import { parseIntent } from "../intent/client.js";
import { mergeEntry } from "../modelwriter/index.js";
import {
  createChangeBranch,
  writeMultipleAndCommit,
  pushBranch,
  openPullRequest,
  returnToMain,
} from "../gitprovider/index.js";
import { ensureEnvironmentWiring } from "../moduleScaffold/generators/environmentWiringGenerator.js";

/**
 * The full Phase 3 pipeline (parse -> validate -> merge -> branch -> commit
 * -> push -> PR), extracted as a pure-ish orchestration function so both
 * cli/propose.ts and api/server.ts call the exact same logic instead of
 * duplicating it. No console output here — callers decide how to present
 * the result (CLI prints it, the API returns it as JSON).
 *
 * Same safety properties as always: never touches main directly, never
 * merges/applies anything, blocked from proposing to any environment not
 * in ALLOWED_ENVIRONMENTS.
 */
export type ProposeOutcome =
  | { status: "clarification_needed"; question: string }
  | { status: "no_action"; message: string }
  | { status: "validation_failed"; errors: string[] }
  | { status: "environment_blocked"; environment: string; allowed: string[] }
  | { status: "merged_file_invalid"; errors: string[] }
  | {
      status: "pr_opened";
      resourceType: string;
      environment: string;
      key: string;
      fields: Record<string, unknown>;
      branch: string;
      prUrl: string;
    }
  | {
      status: "pushed_no_pr";
      resourceType: string;
      environment: string;
      key: string;
      fields: Record<string, unknown>;
      branch: string;
      compareUrl: string | null;
    };

export async function proposeInfrastructureChange(
  message: string,
  requesterId?: string
): Promise<ProposeOutcome> {
  const allowedEnvironments = (process.env.ALLOWED_ENVIRONMENTS ?? "dev")
    .split(",")
    .map((e) => e.trim());

  const result = await parseIntent([{ role: "user", content: message }]);

  if (result.kind === "clarification") {
    return { status: "clarification_needed", question: result.question };
  }
  if (result.kind === "no_action") {
    return { status: "no_action", message: result.message };
  }

  if (!result.validation.valid) {
    return { status: "validation_failed", errors: result.validation.errors };
  }

  if (!allowedEnvironments.includes(result.environment)) {
    return {
      status: "environment_blocked",
      environment: result.environment,
      allowed: allowedEnvironments,
    };
  }

  const merge = mergeEntry(
    result.resourceType,
    result.environment,
    result.key,
    result.fields
  );
  if (!merge.validation.valid) {
    return { status: "merged_file_invalid", errors: merge.validation.errors };
  }

  const branchPrefix = `chatbot/${result.environment}-${result.key}`;
  const branch = createChangeBranch(branchPrefix);

  // First entry ever proposed for this resource type: main.tf has no
  // `module "<name>"` block reading it yet. Wire it in the same commit
  // instead of leaving that as a manual follow-up step.
  const wiring = ensureEnvironmentWiring(result.resourceType, result.environment);

  const requestedBy = requesterId ? `\nRequested by: ${requesterId}` : "";
  const wiringNote = wiring
    ? `\n\nFirst ${result.resourceType} entry for this environment — also wires ` +
      `the module into environments/${result.environment}/main.tf.`
    : "";
  const commitMessage =
    `Add ${result.key} ${result.resourceType} (${result.environment})\n\n` +
    `Proposed via chatbot from: "${message}"${requestedBy}${wiringNote}\n\n` +
    `Schema-validated before commit; not yet reviewed by a human.`;
  const files = [{ filePath: merge.filePath, content: merge.after }];
  if (wiring) files.push(wiring);
  writeMultipleAndCommit(files, commitMessage);

  pushBranch(branch);

  const prTitle = `Add ${result.key} ${result.resourceType} (${result.environment})`;
  const prBody =
    `**Generated by chatbot — human review required.**\n\n` +
    `Original request: "${message}"${requestedBy}${wiringNote}\n\n` +
    `Resource type: \`${result.resourceType}\`\n` +
    `Environment: \`${result.environment}\`\n` +
    `Key: \`${result.key}\`\n\n` +
    "```json\n" +
    JSON.stringify(result.fields, null, 2) +
    "\n```";
  const pr = openPullRequest(branch, prTitle, prBody);

  returnToMain();

  if (pr.prUrl) {
    return {
      status: "pr_opened",
      resourceType: result.resourceType,
      environment: result.environment,
      key: result.key,
      fields: result.fields,
      branch,
      prUrl: pr.prUrl,
    };
  }
  return {
    status: "pushed_no_pr",
    resourceType: result.resourceType,
    environment: result.environment,
    key: result.key,
    fields: result.fields,
    branch,
    compareUrl: pr.compareUrl,
  };
}
